[package]
name = "speedy"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
ctrlc = "3.4"
indicatif = "0.18.0"
notify-rust = "4.8"
rayon = "1.7"
walkdir = "2.3"
num_cpus = "1.15"
